nurun_system:
    resource: "@NurunSystemBundle/Controller/"
    type:     annotation
    prefix:   /

nurun_rh:
    resource: "@NurunRhBundle/Resources/config/routing.yml"
    prefix:   /rh

main:
    pattern: /
    defaults:  { _controller: NurunRhBundle:Conseiller:index, page: 1 }
    requirements:
        page: \d*

logout:
    pattern:   /logout

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_register:
   resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
   prefix: /register

fos_user_resetting:
   resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
   prefix: /resetting

fos_user_change_password:
   resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
   prefix: /profile
