# app/config/security.yml

security:
    erase_credentials: false
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext
        Nurun\Bundle\UserBundle\Entity\User: sha512

    role_hierarchy:
        ROLE_RDP:         [ROLE_USER]
        ROLE_ADMIN:       [ROLE_RDP]
        ROLE_GESTION:     [ROLE_ADMIN]
        ROLE_ROOT:        [ROLE_GESTION]
        ROLE_SUPER_ADMIN: [ROLE_ROOT, ROLE_ALLOWED_TO_SWITCH]

    providers:
        chain_provider:
            chain:
                providers: [fos_userbundle, fr3d_ldapbundle]
        fr3d_ldapbundle:
            id: fr3d_ldap.security.user.provider
        fos_userbundle:
            id: fos_user.user_manager
    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false
        backend:
            pattern: ^/backend
            logout:
                path:   logout
                target: login
            form_login:
                check_path: login_check
                login_path: login
        main:
            pattern:   ^/
            fr3d_ldap: ~
            form_login:
                provider: fos_userbundle
                csrf_provider: form.csrf_provider
                always_use_default_target_path: true
                default_target_path: /rh/accueil
            logout: true
            remember_me:
                secret: '%secret%'
                lifetime: 604800
                path: /
            anonymous: true
    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
